FROM node:6

ADD ./frontend /home/httpd/frontend
WORKDIR /home/httpd/frontend

RUN npm install -g gulp
RUN npm install
RUN npm rebuild node-sass

RUN gulp build
RUN npm install http-server

CMD node node_modules/http-server/bin/http-server static -p 80 --cors
