"""Add create_at and updated_at to all models

Revision ID: 150e17e5c774
Revises: 734b944fd3a7
Create Date: 2016-08-16 21:31:48.166801

"""

# revision identifiers, used by Alembic.
revision = '150e17e5c774'
down_revision = '734b944fd3a7'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auto_advertisement', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('auto_advertisement', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('auto_brand', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('auto_brand', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('auto_complectation', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('auto_complectation', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('auto_model', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('auto_model', sa.Column('updated_at', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auto_model', 'updated_at')
    op.drop_column('auto_model', 'created_at')
    op.drop_column('auto_complectation', 'updated_at')
    op.drop_column('auto_complectation', 'created_at')
    op.drop_column('auto_brand', 'updated_at')
    op.drop_column('auto_brand', 'created_at')
    op.drop_column('auto_advertisement', 'updated_at')
    op.drop_column('auto_advertisement', 'created_at')
    ### end Alembic commands ###
