"""Add origin_url to OriginAdvertisement

Revision ID: 25b4d8faba3b
Revises: c02a163f1a53
Create Date: 2016-08-10 14:18:02.041272

"""

# revision identifiers, used by Alembic.
revision = '25b4d8faba3b'
down_revision = 'c02a163f1a53'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auto_originadvertisement', sa.Column('origin_url', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auto_originadvertisement', 'origin_url')
    ### end Alembic commands ###
