"""Add autoincrement for id

Revision ID: 48c4c0104445
Revises: 150e17e5c774
Create Date: 2016-08-16 22:11:48.668749

"""

# revision identifiers, used by Alembic.
revision = '48c4c0104445'
down_revision = '150e17e5c774'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
