"""Add origin_url to advertisement model

Revision ID: 4b22022a86f5
Revises: 48c4c0104445
Create Date: 2016-08-16 22:42:32.458432

"""

# revision identifiers, used by Alembic.
revision = '4b22022a86f5'
down_revision = '48c4c0104445'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auto_advertisement', sa.Column('origin_url', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auto_advertisement', 'origin_url')
    ### end Alembic commands ###
