"""Base models

Revision ID: 734b944fd3a7
Revises: 
Create Date: 2016-08-15 23:43:35.411885

"""

# revision identifiers, used by Alembic.
revision = '734b944fd3a7'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auto_brand',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='name_uc')
    )
    op.create_table('auto_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['auto_brand.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'brand_id', name='name_brand_uc')
    )
    op.create_table('auto_originbrand',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('origin', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('real_instance', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['real_instance'], ['auto_brand.id'], ),
    sa.PrimaryKeyConstraint('id', 'origin'),
    sa.UniqueConstraint('origin', 'name')
    )
    op.create_index(op.f('ix_auto_originbrand_origin'), 'auto_originbrand', ['origin'], unique=False)
    op.create_table('auto_complectation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['auto_model.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'model_id', name='name_model_uc')
    )
    op.create_table('auto_originmodel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('origin', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('real_instance', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['brand_id', 'origin'], ['auto_originbrand.id', 'auto_originbrand.origin'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['real_instance'], ['auto_model.id'], ),
    sa.PrimaryKeyConstraint('id', 'origin'),
    sa.UniqueConstraint('origin', 'name', 'brand_id', name='origin_name_brand_uc')
    )
    op.create_index(op.f('ix_auto_originmodel_origin'), 'auto_originmodel', ['origin'], unique=False)
    op.create_table('auto_advertisement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('is_new', sa.Boolean(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('preview', sa.String(), nullable=True),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('complectation_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['complectation_id'], ['auto_complectation.id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['auto_model.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('auto_origincomplectation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('origin', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('real_instance', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['model_id', 'origin'], ['auto_originmodel.id', 'auto_originmodel.origin'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['real_instance'], ['auto_complectation.id'], ),
    sa.PrimaryKeyConstraint('id', 'origin'),
    sa.UniqueConstraint('origin', 'name', 'model_id', name='origin_name_model_uc')
    )
    op.create_index(op.f('ix_auto_origincomplectation_origin'), 'auto_origincomplectation', ['origin'], unique=False)
    op.create_table('auto_originadvertisement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('is_new', sa.Boolean(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('preview', sa.String(), nullable=True),
    sa.Column('origin', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('complectation_id', sa.Integer(), nullable=True),
    sa.Column('origin_url', sa.String(), nullable=True),
    sa.Column('real_instance', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['complectation_id', 'origin'], ['auto_origincomplectation.id', 'auto_origincomplectation.origin'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['model_id', 'origin'], ['auto_originmodel.id', 'auto_originmodel.origin'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['real_instance'], ['auto_advertisement.id'], ),
    sa.PrimaryKeyConstraint('id', 'origin')
    )
    op.create_index(op.f('ix_auto_originadvertisement_origin'), 'auto_originadvertisement', ['origin'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_auto_originadvertisement_origin'), table_name='auto_originadvertisement')
    op.drop_table('auto_originadvertisement')
    op.drop_index(op.f('ix_auto_origincomplectation_origin'), table_name='auto_origincomplectation')
    op.drop_table('auto_origincomplectation')
    op.drop_table('auto_advertisement')
    op.drop_index(op.f('ix_auto_originmodel_origin'), table_name='auto_originmodel')
    op.drop_table('auto_originmodel')
    op.drop_table('auto_complectation')
    op.drop_index(op.f('ix_auto_originbrand_origin'), table_name='auto_originbrand')
    op.drop_table('auto_originbrand')
    op.drop_table('auto_model')
    op.drop_table('auto_brand')
    ### end Alembic commands ###
