"""Add complectation models

Revision ID: a24972a141ba
Revises: 4b22022a86f5
Create Date: 2016-11-10 14:25:08.823283

"""

# revision identifiers, used by Alembic.
revision = 'a24972a141ba'
down_revision = '4b22022a86f5'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auto_bodytype',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('auto_drivetype',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('auto_energysource',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('auto_enginecylindersposition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('auto_engineposition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('auto_gearboxtype',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('auto_steeramplifier',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('auto_originbodytype',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('origin', sa.String(), nullable=False),
    sa.Column('real_instance', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['real_instance'], ['auto_bodytype.id'], ),
    sa.PrimaryKeyConstraint('id', 'origin'),
    sa.UniqueConstraint('name', 'origin')
    )
    op.create_index(op.f('ix_auto_originbodytype_origin'), 'auto_originbodytype', ['origin'], unique=False)
    op.create_table('auto_origindrivetype',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('origin', sa.String(), nullable=False),
    sa.Column('real_instance', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['real_instance'], ['auto_drivetype.id'], ),
    sa.PrimaryKeyConstraint('id', 'origin'),
    sa.UniqueConstraint('name', 'origin')
    )
    op.create_index(op.f('ix_auto_origindrivetype_origin'), 'auto_origindrivetype', ['origin'], unique=False)
    op.create_table('auto_originenergysource',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('origin', sa.String(), nullable=False),
    sa.Column('real_instance', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['real_instance'], ['auto_energysource.id'], ),
    sa.PrimaryKeyConstraint('id', 'origin'),
    sa.UniqueConstraint('name', 'origin')
    )
    op.create_index(op.f('ix_auto_originenergysource_origin'), 'auto_originenergysource', ['origin'], unique=False)
    op.create_table('auto_originenginecylindersposition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('origin', sa.String(), nullable=False),
    sa.Column('real_instance', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['real_instance'], ['auto_enginecylindersposition.id'], ),
    sa.PrimaryKeyConstraint('id', 'origin'),
    sa.UniqueConstraint('name', 'origin')
    )
    op.create_index(op.f('ix_auto_originenginecylindersposition_origin'), 'auto_originenginecylindersposition', ['origin'], unique=False)
    op.create_table('auto_originengineposition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('origin', sa.String(), nullable=False),
    sa.Column('real_instance', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['real_instance'], ['auto_engineposition.id'], ),
    sa.PrimaryKeyConstraint('id', 'origin'),
    sa.UniqueConstraint('name', 'origin')
    )
    op.create_index(op.f('ix_auto_originengineposition_origin'), 'auto_originengineposition', ['origin'], unique=False)
    op.create_table('auto_origingearboxtype',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('origin', sa.String(), nullable=False),
    sa.Column('real_instance', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['real_instance'], ['auto_gearboxtype.id'], ),
    sa.PrimaryKeyConstraint('id', 'origin'),
    sa.UniqueConstraint('name', 'origin')
    )
    op.create_index(op.f('ix_auto_origingearboxtype_origin'), 'auto_origingearboxtype', ['origin'], unique=False)
    op.create_table('auto_originsteeramplifier',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('origin', sa.String(), nullable=False),
    sa.Column('real_instance', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['real_instance'], ['auto_steeramplifier.id'], ),
    sa.PrimaryKeyConstraint('id', 'origin'),
    sa.UniqueConstraint('name', 'origin')
    )
    op.create_index(op.f('ix_auto_originsteeramplifier_origin'), 'auto_originsteeramplifier', ['origin'], unique=False)
    op.create_table('auto_body',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('complectation_id', sa.Integer(), nullable=False),
    sa.Column('body_type_id', sa.Integer(), nullable=True),
    sa.Column('doors', sa.Integer(), nullable=True),
    sa.Column('seats', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['body_type_id'], ['auto_bodytype.id'], ),
    sa.ForeignKeyConstraint(['complectation_id'], ['auto_complectation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('auto_dimensions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('complectation_id', sa.Integer(), nullable=False),
    sa.Column('length', sa.Integer(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('clearance', sa.Integer(), nullable=True),
    sa.Column('curb_weight', sa.Integer(), nullable=True),
    sa.Column('max_allowed_weight', sa.Integer(), nullable=True),
    sa.Column('trunk_volume', sa.Integer(), nullable=True),
    sa.Column('fuel_tank_volume', sa.Integer(), nullable=True),
    sa.Column('wheel_base', sa.Integer(), nullable=True),
    sa.Column('bearing_capacity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['complectation_id'], ['auto_complectation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('auto_dynamiccharacteristics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('complectation_id', sa.Integer(), nullable=False),
    sa.Column('max_velocity', sa.Integer(), nullable=True),
    sa.Column('acceleration_time_to_100', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['complectation_id'], ['auto_complectation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('auto_engine',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('complectation_id', sa.Integer(), nullable=False),
    sa.Column('position_id', sa.Integer(), nullable=True),
    sa.Column('energy_source_id', sa.Integer(), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('cylinders', sa.Integer(), nullable=True),
    sa.Column('cylinders_position_id', sa.Integer(), nullable=True),
    sa.Column('valves_count', sa.Integer(), nullable=True),
    sa.Column('co2_emission', sa.Integer(), nullable=True),
    sa.Column('euro_toxicity_norms', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['complectation_id'], ['auto_complectation.id'], ),
    sa.ForeignKeyConstraint(['cylinders_position_id'], ['auto_enginecylindersposition.id'], ),
    sa.ForeignKeyConstraint(['energy_source_id'], ['auto_energysource.id'], ),
    sa.ForeignKeyConstraint(['position_id'], ['auto_engineposition.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('auto_steering',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('complectation_id', sa.Integer(), nullable=False),
    sa.Column('amplifier_id', sa.Integer(), nullable=True),
    sa.Column('spread_diameter', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['amplifier_id'], ['auto_steeramplifier.id'], ),
    sa.ForeignKeyConstraint(['complectation_id'], ['auto_complectation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('auto_transmission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('complectation_id', sa.Integer(), nullable=False),
    sa.Column('gearbox_type_id', sa.Integer(), nullable=True),
    sa.Column('gears_count', sa.Integer(), nullable=True),
    sa.Column('drive_type_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['complectation_id'], ['auto_complectation.id'], ),
    sa.ForeignKeyConstraint(['drive_type_id'], ['auto_drivetype.id'], ),
    sa.ForeignKeyConstraint(['gearbox_type_id'], ['auto_gearboxtype.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('auto_enginefuelrate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mixed', sa.Integer(), nullable=False),
    sa.Column('urban', sa.Integer(), nullable=True),
    sa.Column('extra_urban', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['auto_engine.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('auto_enginepower',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('horses', sa.Integer(), nullable=True),
    sa.Column('rotations_start', sa.Integer(), nullable=True),
    sa.Column('rotations_end', sa.Integer(), nullable=True),
    sa.Column('max_torque', sa.Integer(), nullable=True),
    sa.Column('max_torque_rotations_start', sa.Integer(), nullable=True),
    sa.Column('max_torque_rotations_end', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['auto_engine.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('auto_originbody',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('complectation_id', sa.Integer(), nullable=False),
    sa.Column('body_type_id', sa.Integer(), nullable=True),
    sa.Column('doors', sa.Integer(), nullable=True),
    sa.Column('seats', sa.Integer(), nullable=True),
    sa.Column('origin', sa.String(), nullable=False),
    sa.Column('real_instance', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['body_type_id', 'origin'], ['auto_originbodytype.id', 'auto_originbodytype.origin'], ),
    sa.ForeignKeyConstraint(['complectation_id', 'origin'], ['auto_origincomplectation.id', 'auto_origincomplectation.origin'], ),
    sa.ForeignKeyConstraint(['real_instance'], ['auto_body.id'], ),
    sa.PrimaryKeyConstraint('id', 'origin')
    )
    op.create_index(op.f('ix_auto_originbody_origin'), 'auto_originbody', ['origin'], unique=False)
    op.create_table('auto_origindimensions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('complectation_id', sa.Integer(), nullable=False),
    sa.Column('length', sa.Integer(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('clearance', sa.Integer(), nullable=True),
    sa.Column('curb_weight', sa.Integer(), nullable=True),
    sa.Column('max_allowed_weight', sa.Integer(), nullable=True),
    sa.Column('trunk_volume', sa.Integer(), nullable=True),
    sa.Column('fuel_tank_volume', sa.Integer(), nullable=True),
    sa.Column('wheel_base', sa.Integer(), nullable=True),
    sa.Column('bearing_capacity', sa.Integer(), nullable=True),
    sa.Column('origin', sa.String(), nullable=False),
    sa.Column('real_instance', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['complectation_id', 'origin'], ['auto_origincomplectation.id', 'auto_origincomplectation.origin'], ),
    sa.ForeignKeyConstraint(['real_instance'], ['auto_dimensions.id'], ),
    sa.PrimaryKeyConstraint('id', 'origin')
    )
    op.create_index(op.f('ix_auto_origindimensions_origin'), 'auto_origindimensions', ['origin'], unique=False)
    op.create_table('auto_origindynamiccharacteristics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('complectation_id', sa.Integer(), nullable=False),
    sa.Column('max_velocity', sa.Integer(), nullable=True),
    sa.Column('acceleration_time_to_100', sa.Integer(), nullable=True),
    sa.Column('origin', sa.String(), nullable=False),
    sa.Column('real_instance', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['complectation_id', 'origin'], ['auto_origincomplectation.id', 'auto_origincomplectation.origin'], ),
    sa.ForeignKeyConstraint(['real_instance'], ['auto_dynamiccharacteristics.id'], ),
    sa.PrimaryKeyConstraint('id', 'origin')
    )
    op.create_index(op.f('ix_auto_origindynamiccharacteristics_origin'), 'auto_origindynamiccharacteristics', ['origin'], unique=False)
    op.create_table('auto_originengine',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('complectation_id', sa.Integer(), nullable=False),
    sa.Column('position_id', sa.Integer(), nullable=True),
    sa.Column('energy_source_id', sa.Integer(), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('cylinders', sa.Integer(), nullable=True),
    sa.Column('cylinders_position_id', sa.Integer(), nullable=True),
    sa.Column('valves_count', sa.Integer(), nullable=True),
    sa.Column('co2_emission', sa.Integer(), nullable=True),
    sa.Column('euro_toxicity_norms', sa.Integer(), nullable=True),
    sa.Column('origin', sa.String(), nullable=False),
    sa.Column('real_instance', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['complectation_id', 'origin'], ['auto_origincomplectation.id', 'auto_origincomplectation.origin'], ),
    sa.ForeignKeyConstraint(['cylinders_position_id', 'origin'], ['auto_originenginecylindersposition.id', 'auto_originenginecylindersposition.origin'], ),
    sa.ForeignKeyConstraint(['energy_source_id', 'origin'], ['auto_originenergysource.id', 'auto_originenergysource.origin'], ),
    sa.ForeignKeyConstraint(['position_id', 'origin'], ['auto_originengineposition.id', 'auto_originengineposition.origin'], ),
    sa.ForeignKeyConstraint(['real_instance'], ['auto_engine.id'], ),
    sa.PrimaryKeyConstraint('id', 'origin')
    )
    op.create_index(op.f('ix_auto_originengine_origin'), 'auto_originengine', ['origin'], unique=False)
    op.create_table('auto_originsteering',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('complectation_id', sa.Integer(), nullable=False),
    sa.Column('amplifier_id', sa.Integer(), nullable=True),
    sa.Column('spread_diameter', sa.Integer(), nullable=True),
    sa.Column('origin', sa.String(), nullable=False),
    sa.Column('real_instance', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['amplifier_id', 'origin'], ['auto_originsteeramplifier.id', 'auto_originsteeramplifier.origin'], ),
    sa.ForeignKeyConstraint(['complectation_id', 'origin'], ['auto_origincomplectation.id', 'auto_origincomplectation.origin'], ),
    sa.ForeignKeyConstraint(['real_instance'], ['auto_steering.id'], ),
    sa.PrimaryKeyConstraint('id', 'origin')
    )
    op.create_index(op.f('ix_auto_originsteering_origin'), 'auto_originsteering', ['origin'], unique=False)
    op.create_table('auto_origintransmission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('complectation_id', sa.Integer(), nullable=False),
    sa.Column('gearbox_type_id', sa.Integer(), nullable=True),
    sa.Column('gears_count', sa.Integer(), nullable=True),
    sa.Column('drive_type_id', sa.Integer(), nullable=True),
    sa.Column('origin', sa.String(), nullable=False),
    sa.Column('real_instance', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['complectation_id', 'origin'], ['auto_origincomplectation.id', 'auto_origincomplectation.origin'], ),
    sa.ForeignKeyConstraint(['drive_type_id', 'origin'], ['auto_origindrivetype.id', 'auto_origindrivetype.origin'], ),
    sa.ForeignKeyConstraint(['gearbox_type_id', 'origin'], ['auto_origingearboxtype.id', 'auto_origingearboxtype.origin'], ),
    sa.ForeignKeyConstraint(['real_instance'], ['auto_transmission.id'], ),
    sa.PrimaryKeyConstraint('id', 'origin')
    )
    op.create_index(op.f('ix_auto_origintransmission_origin'), 'auto_origintransmission', ['origin'], unique=False)
    op.create_table('auto_originenginefuelrate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mixed', sa.Integer(), nullable=False),
    sa.Column('urban', sa.Integer(), nullable=True),
    sa.Column('extra_urban', sa.Integer(), nullable=True),
    sa.Column('origin', sa.String(), nullable=False),
    sa.Column('real_instance', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id', 'origin'], ['auto_originengine.id', 'auto_originengine.origin'], ),
    sa.ForeignKeyConstraint(['real_instance'], ['auto_enginefuelrate.id'], ),
    sa.PrimaryKeyConstraint('id', 'origin')
    )
    op.create_index(op.f('ix_auto_originenginefuelrate_origin'), 'auto_originenginefuelrate', ['origin'], unique=False)
    op.create_table('auto_originenginepower',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('horses', sa.Integer(), nullable=True),
    sa.Column('rotations_start', sa.Integer(), nullable=True),
    sa.Column('rotations_end', sa.Integer(), nullable=True),
    sa.Column('max_torque', sa.Integer(), nullable=True),
    sa.Column('max_torque_rotations_start', sa.Integer(), nullable=True),
    sa.Column('max_torque_rotations_end', sa.Integer(), nullable=True),
    sa.Column('origin', sa.String(), nullable=False),
    sa.Column('real_instance', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id', 'origin'], ['auto_originengine.id', 'auto_originengine.origin'], ),
    sa.ForeignKeyConstraint(['real_instance'], ['auto_enginepower.id'], ),
    sa.PrimaryKeyConstraint('id', 'origin')
    )
    op.create_index(op.f('ix_auto_originenginepower_origin'), 'auto_originenginepower', ['origin'], unique=False)
    op.drop_column('auto_complectation', 'updated_at')
    op.drop_column('auto_complectation', 'created_at')
    op.drop_column('auto_origincomplectation', 'updated_at')
    op.drop_column('auto_origincomplectation', 'created_at')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auto_origincomplectation', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('auto_origincomplectation', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('auto_complectation', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('auto_complectation', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_auto_originenginepower_origin'), table_name='auto_originenginepower')
    op.drop_table('auto_originenginepower')
    op.drop_index(op.f('ix_auto_originenginefuelrate_origin'), table_name='auto_originenginefuelrate')
    op.drop_table('auto_originenginefuelrate')
    op.drop_index(op.f('ix_auto_origintransmission_origin'), table_name='auto_origintransmission')
    op.drop_table('auto_origintransmission')
    op.drop_index(op.f('ix_auto_originsteering_origin'), table_name='auto_originsteering')
    op.drop_table('auto_originsteering')
    op.drop_index(op.f('ix_auto_originengine_origin'), table_name='auto_originengine')
    op.drop_table('auto_originengine')
    op.drop_index(op.f('ix_auto_origindynamiccharacteristics_origin'), table_name='auto_origindynamiccharacteristics')
    op.drop_table('auto_origindynamiccharacteristics')
    op.drop_index(op.f('ix_auto_origindimensions_origin'), table_name='auto_origindimensions')
    op.drop_table('auto_origindimensions')
    op.drop_index(op.f('ix_auto_originbody_origin'), table_name='auto_originbody')
    op.drop_table('auto_originbody')
    op.drop_table('auto_enginepower')
    op.drop_table('auto_enginefuelrate')
    op.drop_table('auto_transmission')
    op.drop_table('auto_steering')
    op.drop_table('auto_engine')
    op.drop_table('auto_dynamiccharacteristics')
    op.drop_table('auto_dimensions')
    op.drop_table('auto_body')
    op.drop_index(op.f('ix_auto_originsteeramplifier_origin'), table_name='auto_originsteeramplifier')
    op.drop_table('auto_originsteeramplifier')
    op.drop_index(op.f('ix_auto_origingearboxtype_origin'), table_name='auto_origingearboxtype')
    op.drop_table('auto_origingearboxtype')
    op.drop_index(op.f('ix_auto_originengineposition_origin'), table_name='auto_originengineposition')
    op.drop_table('auto_originengineposition')
    op.drop_index(op.f('ix_auto_originenginecylindersposition_origin'), table_name='auto_originenginecylindersposition')
    op.drop_table('auto_originenginecylindersposition')
    op.drop_index(op.f('ix_auto_originenergysource_origin'), table_name='auto_originenergysource')
    op.drop_table('auto_originenergysource')
    op.drop_index(op.f('ix_auto_origindrivetype_origin'), table_name='auto_origindrivetype')
    op.drop_table('auto_origindrivetype')
    op.drop_index(op.f('ix_auto_originbodytype_origin'), table_name='auto_originbodytype')
    op.drop_table('auto_originbodytype')
    op.drop_table('auto_steeramplifier')
    op.drop_table('auto_gearboxtype')
    op.drop_table('auto_engineposition')
    op.drop_table('auto_enginecylindersposition')
    op.drop_table('auto_energysource')
    op.drop_table('auto_drivetype')
    op.drop_table('auto_bodytype')
    ### end Alembic commands ###
