"""Add preview

Revision ID: c02a163f1a53
Revises: e53b82cbd7f1
Create Date: 2016-08-09 20:23:47.582433

"""

# revision identifiers, used by Alembic.
revision = 'c02a163f1a53'
down_revision = 'e53b82cbd7f1'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auto_advertisement', sa.Column('preview', sa.String(), nullable=True))
    op.add_column('auto_originadvertisement', sa.Column('preview', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auto_originadvertisement', 'preview')
    op.drop_column('auto_advertisement', 'preview')
    ### end Alembic commands ###
