"""Add tables for State model

Revision ID: cf5fff263429
Revises: a24972a141ba
Create Date: 2017-03-10 15:50:21.768340

"""

# revision identifiers, used by Alembic.
revision = 'cf5fff263429'
down_revision = 'a24972a141ba'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auto_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('auto_originstate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('origin', sa.String(), nullable=False),
    sa.Column('real_instance', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['real_instance'], ['auto_state.id'], ),
    sa.PrimaryKeyConstraint('id', 'origin'),
    sa.UniqueConstraint('origin', 'name')
    )
    op.create_index(op.f('ix_auto_originstate_origin'), 'auto_originstate', ['origin'], unique=False)
    op.add_column('auto_advertisement', sa.Column('state_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'auto_advertisement', 'auto_state', ['state_id'], ['id'])
    op.alter_column('auto_complectation', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('auto_originadvertisement', sa.Column('state_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'auto_originadvertisement', 'auto_originstate', ['state_id', 'origin'], ['id', 'origin'], onupdate='CASCADE', ondelete='SET NULL')
    op.alter_column('auto_origincomplectation', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('auto_origincomplectation', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(None, 'auto_originadvertisement', type_='foreignkey')
    op.drop_column('auto_originadvertisement', 'state_id')
    op.alter_column('auto_complectation', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(None, 'auto_advertisement', type_='foreignkey')
    op.drop_column('auto_advertisement', 'state_id')
    op.drop_index(op.f('ix_auto_originstate_origin'), table_name='auto_originstate')
    op.drop_table('auto_originstate')
    op.drop_table('auto_state')
    ### end Alembic commands ###
