"""Add created_at and updated_at fields

Revision ID: e53b82cbd7f1
Revises: 1a73c4af1c34
Create Date: 2016-08-04 10:53:15.247087

"""

# revision identifiers, used by Alembic.
revision = 'e53b82cbd7f1'
down_revision = '1a73c4af1c34'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auto_originadvertisement', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('auto_originadvertisement', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('auto_originbrand', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('auto_originbrand', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('auto_origincomplectation', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('auto_origincomplectation', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('auto_originmodel', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('auto_originmodel', sa.Column('updated_at', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auto_originmodel', 'updated_at')
    op.drop_column('auto_originmodel', 'created_at')
    op.drop_column('auto_origincomplectation', 'updated_at')
    op.drop_column('auto_origincomplectation', 'created_at')
    op.drop_column('auto_originbrand', 'updated_at')
    op.drop_column('auto_originbrand', 'created_at')
    op.drop_column('auto_originadvertisement', 'updated_at')
    op.drop_column('auto_originadvertisement', 'created_at')
    ### end Alembic commands ###
